## How to find a inverse and transpose using python 

# Inverse of matrix 

$ A (inv(A)) = I $


```
if det(A) != 0
    A-1 = adj(A)/det(A)
else
    "Inverse doesn't exist"  

```

In [34]:
import numpy as np
import sys

In [2]:
# let's first compute it with numpy
# Suppose A is 2x2 matrix let's see

A = np.array([[3,4] , [2,16]])

In [3]:
Ainv = np.linalg.inv(A)

In [4]:
Ainv

array([[ 0.4  , -0.1  ],
       [-0.05 ,  0.075]])

In [5]:
I = A* Ainv
I

array([[ 1.2, -0.4],
       [-0.1,  1.2]])

In [35]:
# let's compute it without numpy
## Let's first define Helper functions first.

def print_matrix(A ,title=None):
    if title != None:
        print(title)
    
    for row in A:
        print([round(x , 2)+0 for x in row])

In [31]:
def zeros_matrix(r , c):
    A = []
    for i in range(r) :
        A.append([])
        for j in range(c):
            A[-1].append(0)
            
    return A

In [33]:
def copy_matrix(M):
    rows = len(M)
    cols = len(M[0])

    MC = zeros_matrix(rows, cols)

    for i in range(rows):
        for j in range(rows):
            MC[i][j] = M[i][j]

    return MC

In [36]:
def matrix_multiply(A , B):
    r1 = len(A)
    c1 = len(A[0])
    
    r2 = len(B)
    c2 = len(B[0])
    
    if r1 !=c2 :
        print('A and B must be of same shape and size')
        sys.exit()
        
    C = zeros_matrix(r1 , c2)
    
    for i in range(r1):
        for j in range(c2):
            total = 0
            for k in range(c1):
                total += A[i][k] * B[k][i]
                
            C[i][j] = total
            
    return C
        

In [39]:
A = np.array([[1,2],[5,4] , [7 ,6]])
B = np.array([[1,2,3] , [4,5,6]])

In [40]:
C = matrix_multiply(A , B)
C

[[9, 9, 9], [30, 30, 30], [57, 57, 57]]

In [41]:
def print_matrices(Action, Title1, M1, Title2, M2):
    print(Action)
    print(Title1, '\t'*int(len(M1)/2)+"\t"*len(M1), Title2)
    for i in range(len(M1)):
        row1 = ['{0:+7.3f}'.format(x) for x in M1[i]]
        row2 = ['{0:+7.3f}'.format(x) for x in M2[i]]
        print(row1,'\t', row2)

In [42]:
A = [[5,4,3,2,1],[4,3,2,1,5],[3,2,9,5,4],[2,1,5,4,3],[1,2,3,4,5]]
I = [[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]]
print_matrices('','A Matrix', A, 'I Matrix', I)


A Matrix 							 I Matrix
[' +5.000', ' +4.000', ' +3.000', ' +2.000', ' +1.000'] 	 [' +1.000', ' +0.000', ' +0.000', ' +0.000', ' +0.000']
[' +4.000', ' +3.000', ' +2.000', ' +1.000', ' +5.000'] 	 [' +0.000', ' +1.000', ' +0.000', ' +0.000', ' +0.000']
[' +3.000', ' +2.000', ' +9.000', ' +5.000', ' +4.000'] 	 [' +0.000', ' +0.000', ' +1.000', ' +0.000', ' +0.000']
[' +2.000', ' +1.000', ' +5.000', ' +4.000', ' +3.000'] 	 [' +0.000', ' +0.000', ' +0.000', ' +1.000', ' +0.000']
[' +1.000', ' +2.000', ' +3.000', ' +4.000', ' +5.000'] 	 [' +0.000', ' +0.000', ' +0.000', ' +0.000', ' +1.000']


In [43]:
AM = copy_matrix(A)
IM = copy_matrix(I)
n = len(AM)

exString = """
Since the matrices won't be the original A and I as we start row operations, 
    the matrices will be called: AM for "A Morphing", and IM for "I Morphing" 
"""
print_matrices(exString, 'AM Matrix', AM, 'IM Matrix', IM)
print()


Since the matrices won't be the original A and I as we start row operations, 
    the matrices will be called: AM for "A Morphing", and IM for "I Morphing" 

AM Matrix 							 IM Matrix
[' +5.000', ' +4.000', ' +3.000', ' +2.000', ' +1.000'] 	 [' +1.000', ' +0.000', ' +0.000', ' +0.000', ' +0.000']
[' +4.000', ' +3.000', ' +2.000', ' +1.000', ' +5.000'] 	 [' +0.000', ' +1.000', ' +0.000', ' +0.000', ' +0.000']
[' +3.000', ' +2.000', ' +9.000', ' +5.000', ' +4.000'] 	 [' +0.000', ' +0.000', ' +1.000', ' +0.000', ' +0.000']
[' +2.000', ' +1.000', ' +5.000', ' +4.000', ' +3.000'] 	 [' +0.000', ' +0.000', ' +0.000', ' +1.000', ' +0.000']
[' +1.000', ' +2.000', ' +3.000', ' +4.000', ' +5.000'] 	 [' +0.000', ' +0.000', ' +0.000', ' +0.000', ' +1.000']



In [44]:
# Run this cell then the next for fd = 0, 1, 2, 3, and 4 for a 5x5 matrix. 
#      Then check for identity matrix in last cell.

fd = 0 # fd stands for focus diagonal OR the current diagonal
fdScaler = 1. / AM[fd][fd]

for j in range(n): # using j to indicate cycling thru columns
    AM[fd][j] = fdScaler * AM[fd][j]
    IM[fd][j] = fdScaler * IM[fd][j]
    
print()
print_matrices('', 'AM Matrix', AM, 'IM Matrix', IM)



AM Matrix 							 IM Matrix
[' +1.000', ' +0.800', ' +0.600', ' +0.400', ' +0.200'] 	 [' +0.200', ' +0.000', ' +0.000', ' +0.000', ' +0.000']
[' +4.000', ' +3.000', ' +2.000', ' +1.000', ' +5.000'] 	 [' +0.000', ' +1.000', ' +0.000', ' +0.000', ' +0.000']
[' +3.000', ' +2.000', ' +9.000', ' +5.000', ' +4.000'] 	 [' +0.000', ' +0.000', ' +1.000', ' +0.000', ' +0.000']
[' +2.000', ' +1.000', ' +5.000', ' +4.000', ' +3.000'] 	 [' +0.000', ' +0.000', ' +0.000', ' +1.000', ' +0.000']
[' +1.000', ' +2.000', ' +3.000', ' +4.000', ' +5.000'] 	 [' +0.000', ' +0.000', ' +0.000', ' +0.000', ' +1.000']


In [48]:
n = len(A)
indices = list(range(n))

for i in indices[0:fd] + indices[fd+1:]: # *** skip row with fd in it.
    crScaler = AM[i][fd] # cr stands for "current row".
    for j in range(n): # cr - crScaler * fdRow, but one element at a time.
        AM[i][j] = AM[i][j] - crScaler * AM[fd][j]
        IM[i][j] = IM[i][j] - crScaler * IM[fd][j]
    
print_matrices('', 'AM Matrix', AM, 'IM Matrix', IM)
print()


AM Matrix 							 IM Matrix
[' +1.000', ' +0.800', ' +0.600', ' +0.400', ' +0.200'] 	 [' +0.200', ' +0.000', ' +0.000', ' +0.000', ' +0.000']
[' +0.000', ' -0.200', ' -0.400', ' -0.600', ' +4.200'] 	 [' -0.800', ' +1.000', ' +0.000', ' +0.000', ' +0.000']
[' +0.000', ' -0.400', ' +7.200', ' +3.800', ' +3.400'] 	 [' -0.600', ' +0.000', ' +1.000', ' +0.000', ' +0.000']
[' +0.000', ' -0.600', ' +3.800', ' +3.200', ' +2.600'] 	 [' -0.400', ' +0.000', ' +0.000', ' +1.000', ' +0.000']
[' +0.000', ' +1.200', ' +2.400', ' +3.600', ' +4.800'] 	 [' -0.200', ' +0.000', ' +0.000', ' +0.000', ' +1.000']



In [49]:
indices = list(range(n)) # to allow flexible row referencing ***
for fd in range(1,n): # fd stands for focus diagonal
    fdScaler = 1.0 / AM[fd][fd]
    # FIRST: scale fd row with fd inverse. 
    for j in range(n): # Use j to indicate column looping.
        AM[fd][j] *= fdScaler
        IM[fd][j] *= fdScaler
    
    # Section to print out current actions:
    string1 = '\nUsing the matrices above, Scale row-{} of AM and IM by '
    string2 = 'diagonal element {} of AM, which is 1/{:+.3f}.\n'
    stringsum = string1 + string2
    val1 = fd+1; val2 = fd+1
    Action = stringsum.format(val1,val2,round(1./fdScaler,3))
    print_matrices(Action, 'AM Matrix', AM, 'IM Matrix', IM)
    print()
    
    # SECOND: operate on all rows except fd row.
    for i in indices[:fd] + indices[fd+1:]: # *** skip row with fd in it.
        crScaler = AM[i][fd] # cr stands for "current row".
        for j in range(n): # cr - crScaler * fdRow, but one element at a time.
            AM[i][j] = AM[i][j] - crScaler * AM[fd][j]
            IM[i][j] = IM[i][j] - crScaler * IM[fd][j]
        
        # Section to print out current actions:
        string1 = 'Using the matrices above, subtract {:+.3f} * row-{} of AM from row-{} of AM, and \n'
        string2 = '\tsubtract {:+.3f} * row-{} of IM from row-{} of IM\n'
        val1 = i+1; val2 = fd+1
        stringsum = string1 + string2
        Action = stringsum.format(crScaler, val2, val1, crScaler, val2, val1)
        print_matrices(Action, 'AM Matrix', AM, 'IM Matrix', IM)
        print()


Using the matrices above, Scale row-2 of AM and IM by diagonal element 2 of AM, which is 1/-0.200.

AM Matrix 							 IM Matrix
[' +1.000', ' +0.800', ' +0.600', ' +0.400', ' +0.200'] 	 [' +0.200', ' +0.000', ' +0.000', ' +0.000', ' +0.000']
[' -0.000', ' +1.000', ' +2.000', ' +3.000', '-21.000'] 	 [' +4.000', ' -5.000', ' -0.000', ' -0.000', ' -0.000']
[' +0.000', ' -0.400', ' +7.200', ' +3.800', ' +3.400'] 	 [' -0.600', ' +0.000', ' +1.000', ' +0.000', ' +0.000']
[' +0.000', ' -0.600', ' +3.800', ' +3.200', ' +2.600'] 	 [' -0.400', ' +0.000', ' +0.000', ' +1.000', ' +0.000']
[' +0.000', ' +1.200', ' +2.400', ' +3.600', ' +4.800'] 	 [' -0.200', ' +0.000', ' +0.000', ' +0.000', ' +1.000']

Using the matrices above, subtract +0.800 * row-2 of AM from row-1 of AM, and 
	subtract +0.800 * row-2 of IM from row-1 of IM

AM Matrix 							 IM Matrix
[' +1.000', ' +0.000', ' -1.000', ' -2.000', '+17.000'] 	 [' -3.000', ' +4.000', ' +0.000', ' +0.000', ' +0.000']
[' -0.000', ' +1.000', ' +2.00

# Transpose using numpy

In [50]:
A = np.array([[2,3,4] , [1,6,2]])
Atranspose = np.transpose(A)
Atranspose

array([[2, 1],
       [3, 6],
       [4, 2]])

In [68]:
def transpose(A):
    r = len(A)
    c = len(A[0])
    B = zeros_matrix(c, r)
    
    for i in range(r):
        for j in range(c):
            B[j][i] = A[i][j]
            
    return B

In [69]:
customA = transpose(A)

In [70]:
Atranspose

array([[2, 1],
       [3, 6],
       [4, 2]])

In [71]:
customA

[[2, 1], [3, 6], [4, 2]]